-- AIFlow Starter schema：products 表 + 默认开启 RLS + 最小策略模板（设计 §3.3）
-- 执行方式：Supabase 控制台 SQL Editor 粘贴执行，或本地 `npm run db:push`

create table if not exists products (
  id bigint generated by default as identity primary key,
  title text not null,
  price numeric(10, 2) not null default 0,
  image_url text,
  created_at timestamptz not null default now()
);

-- 行级安全：默认开启（安全基线，不依赖 key 保密）
alter table products enable row level security;

-- 策略 1：匿名/登录用户可读公开商品表
create policy "products are readable by everyone"
  on products for select using (true);

-- 策略 2：登录用户可写入本人数据（示例：owner 字段方案，可按需调整）
-- alter table products add column owner uuid references auth.users (id);
-- create policy "users insert own products"
--   on products for insert with check (auth.uid() = owner);

-- 种子数据（首次执行时插入，幂等）
insert into products (title, price)
select * from (values
  ('AIFlow 标准件 T 恤', 99.00),
  ('Declarative Shadow DOM 马克杯', 59.00),
  ('零依赖贴纸包', 19.90)
) as seed(title, price)
where not exists (select 1 from products);
